{% set name = "clcache" %}
{% set version = "4.2.0" %}
{% set sha256 = "1bc030b52be969e6b533fdc6d8332e69438bab836b0e5562398aae94138b60a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/frerich/clcache/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - clcache = clcache:main
  skip: True  # [not win or py2k]

requirements:
  build:
    - python

  run:
    - python

test:
  commands:
    - clcache --help

about:
  home: https://github.com/frerich/clcache
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'a compiler cache for Microsoft Visual Studio'

  description: |
    clcache.py is a little Python script which attempts to avoid unnecessary
    recompilation by reusing previously cached object files if possible.
    It is meant to be called instead of the original 'cl.exe' executable.
    The script analyses the command line to decide whether source code is to be compiled.
    If so, a cache will be queried for a previously stored object file.

    If the script is called in an unsupported way (e.g. if the compiler is called for linking),
    the script will simply relay the invocation to the real 'cl.exe' program.

extra:
  recipe-maintainers:
    - edisongustavo
    - tadeu
    - nicoddemus
